version: '3'

services:
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=acadamiaDB
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080